### ISSUE TITLE
rivers.geojson contains only 2 characters, model building crashes

### ISSUE THREAD

**Issue by markhegnauer** [Deltares/hydro-engine#2]
Run the hydroengine for teh Chao Phraya in Thailand, the created rivers.geojson only contains 2 characters. The model building scripts crashes because of this. The input geojson (settings.json) and the rivers file (rivers.geojson) are attached to this issue.

[issue.zip](https://github.com/Deltares/hydro-engine/files/1446108/issue.zip)

**Comment by gena** [comment]
> settings.json

```json
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "cellsize": 0.01
      },
      "geometry": {
        "type": "Point",
        "coordinates": [
          100.53709030151367,
          13.635310367863752
        ]
      }
    }
  ]
}
```

Output (error):

```json
]}
```

**Comment by gena** [comment]
Looks like the following QGIS issue: https://gis.stackexchange.com/questions/90218/qgis-spatial-join-numeric-values-change-to-negative-values. Some basin ids turn into negative numbers. Rerunning everything ...
