### ISSUE TITLE
Rivers do not connect correctly

### ISSUE THREAD

**Issue by markhegnauer** [Deltares/hydro-engine#3]
For larger rivers like Rhine and Nile, the created model is not correct. The river network that is derived, is not continuous (i.e. the rivers are not well connected from upstream to downstream). Attached, an example output file for the Rhine (wflow_streamorder.map). The issue might be caused by a wrong shapefile that is used for the burn-in process (?).

[issue2.zip](https://github.com/Deltares/hydro-engine/files/1446119/issue2.zip)

**Comment by gena** [comment]
Will check if returned river polylines are connected

**Comment by gena** [comment]
Can't reproduce, rivers polyline looks fine, see [issues/#003](https://github.com/Deltares/hydro-engine/tree/master/issues/%23003) It looks like a bug is somewhere else, maybe during river burning.
